package com.example.mvvmdemo.utils.enums

import com.example.mvvmdemo.utils.constants.AppConst

enum class AppConfigurationType private constructor(
    override val id: Int,
    internal val value: String
) :
    IdentifierType<Int> {

    PAGE_SIZE_LIST_VERTICAL_SMALL(AppConst.NUMBER.ONE, "PAGE_SIZE_LIST_VERTICAL_SMALL"),
    PAGE_SIZE_LIST_VERTICAL_LARGE(AppConst.NUMBER.TWO, "PAGE_SIZE_LIST_VERTICAL_LARGE"),
    PAGE_SIZE_LIST_HORIZONTAL_SMALL(AppConst.NUMBER.THREE, "PAGE_SIZE_LIST_HORIZONTAL_SMALL"),
    PAGE_SIZE_LIST_HORIZONTAL_LARGE(AppConst.NUMBER.FOUR, "PAGE_SIZE_LIST_HORIZONTAL_LARGE"),
    PAGE_SIZE_GRID_VERTICAL_SMALL(AppConst.NUMBER.FIVE, "PAGE_SIZE_GRID_VERTICAL_SMALL"),
    PAGE_SIZE_GRID_VERTICAL_LARGE(AppConst.NUMBER.SIX, "PAGE_SIZE_GRID_VERTICAL_LARGE"),
    PAGE_SIZE_GRID_HORIZONTAL_SMALL(AppConst.NUMBER.SEVEN, "PAGE_SIZE_GRID_HORIZONTAL_SMALL"),
    PAGE_SIZE_GRID_HORIZONTAL_LARGE(AppConst.NUMBER.EIGHT, "PAGE_SIZE_GRID_HORIZONTAL_LARGE"),

    MAX_IMAGE_SIZE_ORIGINAL(AppConst.NUMBER.NINE, "MAX_IMAGE_SIZE_ORIGINAL"),
    MAX_IMAGE_SIZE_THUMBNAIL(AppConst.NUMBER.TEN, "MAX_IMAGE_SIZE_THUMBNAIL"),
    IMAGE_COMPRESSION_QUALITY_ORIGINAL(AppConst.NUMBER.ELEVEN, "IMAGE_COMPRESSION_QUALITY_ORIGINAL"),
    IMAGE_COMPRESSION_QUALITY_THUMBNAIL(AppConst.NUMBER.TWELVE, "IMAGE_COMPRESSION_QUALITY_THUMBNAIL"),

    RESEND_OTP_DURATION(AppConst.NUMBER.THIRTEEN, "RESEND_OTP_DURATION"),

    INSURED_PHOTOS_MAX_UPLOAD(AppConst.NUMBER.FOURTEEN, "INSURED_PHOTOS_MAX_UPLOAD"),
    COMPANY_CONTACT_NUMBER(AppConst.NUMBER.FIFTEEN, "COMPANY_CONTACT_NUMBER"),
    COMPANY_CONTACT_COUNTRY_CODE(AppConst.NUMBER.SIXTEEN, "COMPANY_CONTACT_COUNTRY_CODE"),
    APP_USER_TYPE(AppConst.NUMBER.SEVENTEEN, "home-owner");

    override fun toString(): String = this.value

    companion object {
        fun valueOf(id: Int): AppConfigurationType? = EnumHelper.INSTANCE.valueOf(id, values())
    }
}
